#!/usr/bin/python3
"""
5-island_perimeter
"""


def island_perimeter(grid):
    """
    island_perimeter function calculates the perimeter of an island
    in a grid of 1's (land) and 0's (water).

    Args:
        grid (List[List[int]]): 2D grid representing the island

    Returns:
        int: perimeter of the island
    """
    perimeter = 0
    for row in range(len(grid)):
        for col in range(len(grid[0])):
            if grid[row][col] == 1:
                perimeter += 4
                if row > 0 and grid[row - 1][col] == 1:
                    perimeter -= 2
                if col > 0 and grid[row][col - 1] == 1:
                    perimeter -= 2
    return perimeter


if __name__ == "__main__":
    grid = [
        [0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 1, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0]
    ]
    print(island_perimeter(grid))
